# -*- coding: utf-8 -*-
"""TFG PABLO MENÉNDEZ PÉREZ

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iXZiojTTccggl9Ck2Uwwx1K9hKLzGYTM
"""

# CONFIGURACIÓN INICIAL Y LIBRERÍAS
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm.auto import tqdm

from sklearn.metrics import mean_absolute_error, mean_squared_error
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from statsmodels.tools.sm_exceptions import ConvergenceWarning

# Configuración visual y limpieza de alertas
plt.style.use('seaborn-v0_8-whitegrid')
warnings.simplefilter('ignore', ConvergenceWarning)
warnings.simplefilter('ignore', UserWarning)
warnings.filterwarnings('ignore', category=DeprecationWarning)

# CARGA DE DATOS (HISTÓRICO Y TEST SECUENCIAL)

# Leemos los datos indicando que las DOS primeras filas son las cabeceras
historico = pd.read_csv("Train_n_val_sets.csv", sep=';', header=[0, 1], index_col=0)
test_real = pd.read_csv("Test_set.csv", sep=';', header=[0, 1], index_col=0)

# Aplanamos las dos cabeceras para crear el identificador único (Tienda_Producto)
historico.columns = [f"{store}_{prod}" for store, prod in historico.columns]
test_real.columns = [f"{store}_{prod}" for store, prod in test_real.columns]

# Limpiamos el nombre del índice
historico.index.name = 'Fecha'
test_real.index.name = 'Fecha'

# Convertimos el índice a formato fecha real de Pandas
historico.index = pd.to_datetime(historico.index)
test_real.index = pd.to_datetime(test_real.index)

# Asignamos la frecuencia temporal (Semanal, empezando en lunes)
historico = historico.asfreq('W-MON')
test_real = test_real.asfreq('W-MON')

print("DIMENSIONES DE LOS DATASETS")
print(f"Histórico Total (Para entrenar Baselines): {historico.shape}")
print(f"Test Real (Para evaluar): {test_real.shape}")

# DIVISIÓN DEL HISTÓRICO EN TRAIN Y VALIDACIÓN (80% - 20%)

# Calculamos el índice donde debe hacerse el corte temporal
corte_val = int(len(historico) * 0.8)

# Dividimos el dataset
train = historico.iloc[:corte_val]

val = historico.iloc[corte_val:]

print(f"Total semanas históricas: {len(historico)}")
print(f"Semanas para Entrenamiento (Train): {len(train)} (del {train.index[0].date()} al {train.index[-1].date()})")
print(f"Semanas para Validación (Val): {len(val)} (del {val.index[0].date()} al {val.index[-1].date()})")

# EXPLORACIÓN DE DATOS (Intermitencia y Estacionalidad)
porcentaje_ceros = (historico == 0).mean() * 100
print(f"Series con 0% de ceros (Venta continua): {(porcentaje_ceros == 0).sum()}")
print(f"Series con más del 50% de ceros: {(porcentaje_ceros > 50).sum()}")

# Visualización de 4 series aleatorias
np.random.seed(42)
series_aleatorias = np.random.choice(historico.columns, 4, replace=False)

fig, axes = plt.subplots(nrows=4, ncols=1, figsize=(14, 14), sharex=True)
fig.subplots_adjust(hspace=0.4)

for i, serie in enumerate(series_aleatorias):
    axes[i].plot(historico.index, historico[serie], marker='o', markersize=4,
                 linestyle='-', linewidth=1.5, color='#1f77b4', alpha=0.8)
    axes[i].fill_between(historico.index, historico[serie], alpha=0.2, color='#1f77b4')

    for year in historico.index.year.unique():
        axes[i].axvline(pd.Timestamp(f'{year}-01-01'), color='red', linestyle='--', alpha=0.5)

    axes[i].set_title(f"Serie de Demanda: {serie}", fontweight='bold')
    axes[i].set_ylabel("Ventas")
    axes[i].set_ylim(bottom=0)

axes[-1].set_xlabel("Fecha (Semanas)", fontweight='bold')
plt.suptitle("Análisis Exploratorio: Estacionalidad e Intermitencia", fontsize=16, y=0.92)
plt.show()

# MODELOS BASELINE (EVALUACIÓN SECUENCIAL ITERATIVA)


# Seasonal Naive (sNaive)
df_completo = pd.concat([historico, test_real])
predicciones_snaive_test = df_completo.shift(52).loc[test_real.index].fillna(0)

# Holt-Winters
predicciones_hw_test = pd.DataFrame(index=test_real.index, columns=historico.columns)

for serie in tqdm(historico.columns):
    hist_actual = historico[serie].copy()

    for fecha in test_real.index:
        try:
            modelo = ExponentialSmoothing(hist_actual, trend='add', seasonal='add',
                                          seasonal_periods=52, initialization_method="estimated").fit()
        except:
            modelo = ExponentialSmoothing(hist_actual, trend=None, seasonal=None,
                                          initialization_method="estimated").fit()

        pred_1_semana = np.maximum(modelo.forecast(steps=1).iloc[0], 0)
        predicciones_hw_test.loc[fecha, serie] = pred_1_semana

        hist_actual.loc[fecha] = test_real.loc[fecha, serie]

predicciones_hw_test = predicciones_hw_test.astype(float)


# GUARDAR RESULTADOS EN DRIVE

import os

ruta_hw = '/content/drive/MyDrive/TFG_Modelos/predicciones_hw_test_baseline.csv'
ruta_snaive = '/content/drive/MyDrive/TFG_Modelos/predicciones_snaive_test_baseline.csv'

os.makedirs('/content/drive/MyDrive/TFG_Modelos', exist_ok=True)

predicciones_hw_test.to_csv(ruta_hw)
predicciones_snaive_test.to_csv(ruta_snaive)

# CELDA PARA CARGAR LOS BASELINES (HW y sNaive) SIN ESPERAR

import pandas as pd
import os

ruta_hw = '/content/drive/MyDrive/TFG_Modelos/predicciones_hw_test_baseline.csv'
ruta_snaive = '/content/drive/MyDrive/TFG_Modelos/predicciones_snaive_test_baseline.csv'

# CARGA DE HOLT-WINTERS
if os.path.exists(ruta_hw):
    predicciones_hw_test = pd.read_csv(ruta_hw, index_col=0)
    predicciones_hw_test.index = pd.to_datetime(predicciones_hw_test.index)
    print(" Holt-Winters cargado correctamente.")
else:
    print("  No se encontró el archivo de Holt-Winters.")

# CARGA DE SEASONAL NAIVE
if os.path.exists(ruta_snaive):
    predicciones_snaive_test = pd.read_csv(ruta_snaive, index_col=0)
    predicciones_snaive_test.index = pd.to_datetime(predicciones_snaive_test.index)
    print("  Seasonal Naive cargado correctamente.")
else:
    print("  No se encontró el archivo de Seasonal Naive.")

# EVALUACIÓN Y VISUALIZACIÓN EN TEST REAL

# Cálculo de errores
errores_snaive = test_real - predicciones_snaive_test
maes_snaive = errores_snaive.abs().mean()
rmses_snaive = (errores_snaive ** 2).mean() ** 0.5

errores_hw = test_real - predicciones_hw_test
maes_hw = errores_hw.abs().mean()
rmses_hw = (errores_hw ** 2).mean() ** 0.5

print(f"sNaive       -> MAE Medio: {maes_snaive.mean():.4f} | RMSE Medio: {rmses_snaive.mean():.4f}")
print(f"Holt-Winters -> MAE Medio: {maes_hw.mean():.4f} | RMSE Medio: {rmses_hw.mean():.4f}")

# Visualización comparativa: Dato Real vs Predicción
np.random.seed(123)
series_vis = np.random.choice(historico.columns, 4, replace=False)

fig, axes = plt.subplots(nrows=4, ncols=1, figsize=(14, 16), sharex=True)
fig.subplots_adjust(hspace=0.4)

for i, serie in enumerate(series_vis):
    contexto = historico[serie].iloc[-20:]

    axes[i].plot(contexto.index, contexto, label='Histórico Reciente', color='#555555', marker='o', markersize=4)
    axes[i].plot(test_real.index, test_real[serie], label='Test (Dato Real)', color='#2ca02c', marker='o', linewidth=2.5)
    axes[i].plot(predicciones_hw_test.index, predicciones_hw_test[serie], label='Pred. Holt-Winters', color='#d62728', linestyle='--', marker='x', linewidth=2)

    axes[i].set_title(f"Evaluación Secuencial en Test Real - Serie: {serie}", fontweight='bold')
    axes[i].set_ylabel("Ventas")
    axes[i].set_ylim(bottom=0)
    axes[i].legend(loc='upper left')

axes[-1].set_xlabel("Fecha (Semanas)", fontweight='bold')
plt.suptitle("Comparativa Visual: Dato Real vs Predicción Holt-Winters", fontsize=16, y=0.92)
plt.show()

!pip install skforecast

!pip install neuralforecast

# ENTRENAMIENTO DE LA FFNN (MLP)

import pandas as pd
from neuralforecast import NeuralForecast
from neuralforecast.models import MLP
from neuralforecast.losses.pytorch import DistributionLoss


# PONEMOS LOS DATOS EN FORMATO "LONG"
train_nixtla = train.copy().astype(float)
test_real_nf = test_real.copy().astype(float)

# Renombramos el índice a 'ds' temporalmente
train_nixtla.index.name = 'ds'

# Pasamos del formato wide a long
df_train_long = train_nixtla.reset_index().melt(id_vars='ds', var_name='unique_id', value_name='y')
df_train_long['ds'] = pd.to_datetime(df_train_long['ds'])

# FFNN (MLP)

modelo_ffnn_nixtla = MLP(
    h=1,
    input_size=15,
    hidden_size=256,
    num_layers=2,
    loss=DistributionLoss(distribution='Poisson'),
    max_steps=500,
    scaler_type='robust',
    learning_rate=1e-3,
    random_seed=42
)

# ENTRENAMOS
nf_ffnn = NeuralForecast(models=[modelo_ffnn_nixtla], freq="W-MON")
nf_ffnn.fit(df=df_train_long)

# PREDICCIÓN ITERATIVA (WALK-FORWARD) Y EVALUACIÓN DE LA FFNN

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

columnas_oficiales = train_nixtla.columns.tolist()
predicciones_ffnn_nf = pd.DataFrame(index=test_real_nf.index, columns=columnas_oficiales, dtype=float)

ventana_long = df_train_long.copy()

nombre_columna_modelo = nf_ffnn.models[0].__class__.__name__

for i, fecha in enumerate(test_real_nf.index):
    # Predicción
    preds = nf_ffnn.predict(df=ventana_long).reset_index()

    # De formato long a wide
    ultima_fecha_pred = preds['ds'].unique()[0]
    preds_fecha = preds[preds['ds'] == ultima_fecha_pred]
    preds_wide = preds_fecha.pivot(index='ds', columns='unique_id', values=nombre_columna_modelo).iloc[0]

    # Extraemos los datos y evitamos negativos
    pred_limpia = preds_wide[columnas_oficiales].values
    pred_limpia = np.maximum(pred_limpia, 0.0)
    predicciones_ffnn_nf.iloc[i, :] = pred_limpia

    # Actualizamos la ventana con el dato de la realidad de esta semana
    fila_real = test_real_nf.iloc[[i]].copy()
    fila_real.index.name = 'ds'
    fila_real_long = fila_real.reset_index().melt(id_vars='ds', var_name='unique_id', value_name='y')
    fila_real_long['ds'] = pd.to_datetime(fila_real_long['ds'])

    ventana_long = pd.concat([ventana_long, fila_real_long], ignore_index=True)

predicciones_ffnn_nf = predicciones_ffnn_nf.astype(float)

# CÁLCULO DE MÉTRICAS
errores_ffnn = test_real_nf - predicciones_ffnn_nf
maes_ffnn = errores_ffnn.abs().mean()
rmses_ffnn = (errores_ffnn ** 2).mean() ** 0.5

print(f"MAE Medio de las {len(columnas_oficiales)} series: {maes_ffnn.mean():.4f}")
print(f"RMSE Medio de las {len(columnas_oficiales)} series: {rmses_ffnn.mean():.4f}")

# VISUALIZACIÓN
np.random.seed(123)
series_vis = np.random.choice(columnas_oficiales, 4, replace=False)

fig, axes = plt.subplots(nrows=4, ncols=1, figsize=(14, 16), sharex=True)
fig.subplots_adjust(hspace=0.4)

for idx, serie in enumerate(series_vis):
    contexto = historico[serie].iloc[-20:].astype(float)

    axes[idx].plot(contexto.index, contexto, label='Histórico Reciente', color='#555555', marker='o', markersize=4)
    axes[idx].plot(test_real_nf.index, test_real_nf[serie], label='Test Real (Verde)', color='#2ca02c', marker='o', linewidth=2.5)
    axes[idx].plot(predicciones_ffnn_nf.index, predicciones_ffnn_nf[serie], label='Pred. FFNN (Azul)', color='#1f77b4', linestyle='--', marker='s', linewidth=2)

    axes[idx].set_title(f"Modelo FFNN (MLP) vs Realidad - Serie: {serie}", fontweight='bold')
    axes[idx].set_ylabel("Ventas")
    axes[idx].set_ylim(bottom=0)
    axes[idx].legend(loc='upper left')

axes[-1].set_xlabel("Fecha (Semanas)", fontweight='bold')
plt.suptitle("Comparativa Visual: Dato Real vs FFNN (MLP con Poisson Loss)", fontsize=16, y=0.92)
plt.show()

# LSTM
from neuralforecast import NeuralForecast

from neuralforecast.models import LSTM

from neuralforecast.losses.pytorch import DistributionLoss


train_nixtla = train.copy().astype(float)

test_real_nf = test_real.copy().astype(float)

train_nixtla.index.name = 'ds'

#Pasamos de 599 columnas a 3 columnas
df_train_long = train_nixtla.reset_index().melt(id_vars='ds', var_name='unique_id', value_name='y')
df_train_long['ds'] = pd.to_datetime(df_train_long['ds'])

# LSTM

modelo_lstm_nixtla = LSTM(

    h=1,
    input_size=15,
    loss=DistributionLoss(distribution='Poisson'),
    max_steps=500,
    scaler_type='robust',
    learning_rate=1e-3,
    random_seed=42
)

#ENTRENAMOS
nf = NeuralForecast(models=[modelo_lstm_nixtla],freq="W-MON")
nf.fit(df=df_train_long)

# PREDICCIÓN ITERATIVA

import matplotlib.pyplot as plt
import numpy as np

columnas_oficiales = train_nixtla.columns.tolist()
predicciones_lstm_nf = pd.DataFrame(index=test_real_nf.index, columns=columnas_oficiales, dtype=float)

# Ventana actual en formato long
ventana_long = df_train_long.copy()

for i, fecha in enumerate(test_real_nf.index):

    preds = nf.predict(df=ventana_long).reset_index()

    # De formato Long a Wide (1 fila, 599 columnas)
    preds_wide = preds.pivot(index='ds', columns='unique_id', values='LSTM').iloc[0]

    pred_limpia = preds_wide[columnas_oficiales].values
    pred_limpia = np.maximum(pred_limpia, 0.0)
    predicciones_lstm_nf.iloc[i, :] = pred_limpia

    # Actualizamos la ventana con el dato de la realidad de esta semana
    fila_real = test_real_nf.iloc[[i]].copy()
    fila_real.index.name = 'ds'
    fila_real_long = fila_real.reset_index().melt(id_vars='ds', var_name='unique_id', value_name='y')
    fila_real_long['ds'] = pd.to_datetime(fila_real_long['ds'])

    ventana_long = pd.concat([ventana_long, fila_real_long], ignore_index=True)

predicciones_lstm_nf = predicciones_lstm_nf.astype(float)

# Métricas
errores_nf = test_real_nf - predicciones_lstm_nf
maes_nf = errores_nf.abs().mean()
rmses_nf = (errores_nf ** 2).mean() ** 0.5

print(f"MAE Medio de las {len(columnas_oficiales)} series: {maes_nf.mean():.4f}")
print(f"RMSE Medio de las {len(columnas_oficiales)} series: {rmses_nf.mean():.4f}")

# Visualización Aleatoria Comparativa
np.random.seed(123)
series_vis = np.random.choice(columnas_oficiales, 4, replace=False)

fig, axes = plt.subplots(nrows=4, ncols=1, figsize=(14, 16), sharex=True)
fig.subplots_adjust(hspace=0.4)

for idx, serie in enumerate(series_vis):
    contexto = historico[serie].iloc[-20:].astype(float)

    axes[idx].plot(contexto.index, contexto, label='Histórico Reciente', color='#555555', marker='o', markersize=4)
    axes[idx].plot(test_real_nf.index, test_real_nf[serie], label='Test Real (Verde)', color='#2ca02c', marker='o', linewidth=2.5)

    axes[idx].plot(predicciones_lstm_nf.index, predicciones_lstm_nf[serie], label='Pred. Nixtla (Azul)', color='#1f77b4', linestyle='--', marker='s', linewidth=2)

    axes[idx].set_title(f"Modelo LSTM (Nixtla VN2) vs Realidad - Serie: {serie}", fontweight='bold')
    axes[idx].set_ylabel("Ventas")
    axes[idx].set_ylim(bottom=0)
    axes[idx].legend(loc='upper left')

axes[-1].set_xlabel("Fecha (Semanas)", fontweight='bold')
plt.suptitle("Comparativa Visual: Dato Real vs LSTM (Formato Long)", fontsize=16, y=0.92)
plt.show()

# Ray Tune (necesario para las clases Auto en NeuralForecast)
!pip install -q "ray[tune]"

# BÚSQUEDA DE HIPERPARÁMETROS (GRID SEARCH) CON AUTO-LSTM

import pandas as pd
from neuralforecast import NeuralForecast
from neuralforecast.auto import AutoLSTM
from neuralforecast.losses.pytorch import DistributionLoss
from ray import tune

train_nixtla = train.copy().astype(float)
test_real_nf = test_real.copy().astype(float)

train_nixtla.index.name = 'ds'
df_train_long = train_nixtla.reset_index().melt(id_vars='ds', var_name='unique_id', value_name='y')
df_train_long['ds'] = pd.to_datetime(df_train_long['ds'])

# DEFINIR EL ESPACIO DE BÚSQUEDA (Grid Search)
lstm_config = {
    # Lags a probar: 15 semanas, 26 semanas y 52 semanas
    "input_size": tune.choice([15, 26, 52]),

    # Capas de la red a probar: 1, 2 o 3
    "encoder_n_layers": tune.choice([1, 2, 3]),

    "encoder_hidden_size": tune.choice([128, 256, 512]),
    "learning_rate": tune.loguniform(1e-4, 1e-2),

    # Parámetros fijos
    "max_steps": 1000,
    "scaler_type": 'robust'
}

# AUTO-LSTM
modelo_auto_lstm = AutoLSTM(
    h=1,
    loss=DistributionLoss(distribution='NegativeBinomial'),
    config=lstm_config,
    num_samples=10,
    search_alg="random"
)

# ENTRENAR
nf_auto = NeuralForecast(models=[modelo_auto_lstm], freq="W-MON")
nf_auto.fit(df=df_train_long)

# PREDICCIÓN ITERATIVA CON EL MEJOR AUTO-LSTM

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

columnas_oficiales = train_nixtla.columns.tolist()
predicciones_auto_lstm = pd.DataFrame(index=test_real_nf.index, columns=columnas_oficiales, dtype=float)
ventana_long = df_train_long.copy()

# OBTENER EL NOMBRE DEL MODELO GANADOR
nombre_columna_modelo = nf_auto.models[0].__class__.__name__

for i, fecha in enumerate(test_real_nf.index):
    # Predicción con el Auto-modelo
    preds = nf_auto.predict(df=ventana_long).reset_index()

    # Transformación
    ultima_fecha_pred = preds['ds'].unique()[0]
    preds_fecha = preds[preds['ds'] == ultima_fecha_pred]
    preds_wide = preds_fecha.pivot(index='ds', columns='unique_id', values=nombre_columna_modelo).iloc[0]

    # Limpieza
    pred_limpia = np.maximum(preds_wide[columnas_oficiales].values, 0.0)
    predicciones_auto_lstm.iloc[i, :] = pred_limpia

    # Actualización (Walk-Forward)
    fila_real = test_real_nf.iloc[[i]].copy()
    fila_real.index.name = 'ds'
    fila_real_long = fila_real.reset_index().melt(id_vars='ds', var_name='unique_id', value_name='y')
    fila_real_long['ds'] = pd.to_datetime(fila_real_long['ds'])

    ventana_long = pd.concat([ventana_long, fila_real_long], ignore_index=True)

    print(f" Semana {i+1}/8 completada: {fecha.date()}")

errores_auto = test_real_nf - predicciones_auto_lstm
maes_auto = errores_auto.abs().mean()
rmses_auto = (errores_auto ** 2).mean() ** 0.5

print(f" RESULTADOS FINALES: {nombre_columna_modelo}")
print(f"MAE Medio (Global):  {maes_auto.mean():.4f}")
print(f"RMSE Medio (Global): {rmses_auto.mean():.4f}")

# ENTRENAMIENTO N-HiTS

import pandas as pd
from neuralforecast import NeuralForecast
from neuralforecast.models import NHITS
from neuralforecast.losses.pytorch import DistributionLoss

train_nixtla = train.copy().astype(float)
test_real_nf = test_real.copy().astype(float)

train_nixtla.index.name = 'ds'
df_train_long = train_nixtla.reset_index().melt(id_vars='ds', var_name='unique_id', value_name='y')
df_train_long['ds'] = pd.to_datetime(df_train_long['ds'])

modelo_nhits = NHITS(
    h=1,
    input_size=15,
    loss=DistributionLoss(distribution='Poisson'),
    max_steps=1000,
    scaler_type='robust',
    learning_rate=1e-3,
    random_seed=42
)

nf_nhits = NeuralForecast(models=[modelo_nhits],freq='W-MON')
nf_nhits.fit(df=df_train_long)

# PREDICCIÓN ITERATIVA CON N-HiTS

import matplotlib.pyplot as plt
import numpy as np


columnas_oficiales = train_nixtla.columns.tolist()
predicciones_nhits_nf = pd.DataFrame(index=test_real_nf.index, columns=columnas_oficiales, dtype=float)

ventana_long = df_train_long.copy()

for i, fecha in enumerate(test_real_nf.index):

    preds = nf_nhits.predict(df=ventana_long).reset_index()

    preds_wide = preds.pivot(index='ds', columns='unique_id', values='NHITS').iloc[0]

    pred_limpia = preds_wide[columnas_oficiales].values
    pred_limpia = np.maximum(pred_limpia, 0.0)
    predicciones_nhits_nf.iloc[i, :] = pred_limpia

    fila_real = test_real_nf.iloc[[i]].copy()
    fila_real.index.name = 'ds'
    fila_real_long = fila_real.reset_index().melt(id_vars='ds', var_name='unique_id', value_name='y')
    fila_real_long['ds'] = pd.to_datetime(fila_real_long['ds'])

    ventana_long = pd.concat([ventana_long, fila_real_long], ignore_index=True)

predicciones_nhits_nf = predicciones_nhits_nf.astype(float)

# Métricas
errores_nhits = test_real_nf - predicciones_nhits_nf
maes_nhits = errores_nhits.abs().mean()
rmses_nhits = (errores_nhits ** 2).mean() ** 0.5

print(f"MAE Medio de las {len(columnas_oficiales)} series: {maes_nhits.mean():.4f}")
print(f"RMSE Medio de las {len(columnas_oficiales)} series: {rmses_nhits.mean():.4f}")

# Visualización
np.random.seed(123)
series_vis = np.random.choice(columnas_oficiales, 4, replace=False)

fig, axes = plt.subplots(nrows=4, ncols=1, figsize=(14, 16), sharex=True)
fig.subplots_adjust(hspace=0.4)

for idx, serie in enumerate(series_vis):
    contexto = historico[serie].iloc[-20:].astype(float)

    axes[idx].plot(contexto.index, contexto, label='Histórico Reciente', color='#555555', marker='o', markersize=4)
    axes[idx].plot(test_real_nf.index, test_real_nf[serie], label='Test Real (Verde)', color='#2ca02c', marker='o', linewidth=2.5)
    axes[idx].plot(predicciones_nhits_nf.index, predicciones_nhits_nf[serie], label='Pred. N-HiTS (Azul)', color='#1f77b4', linestyle='--', marker='s', linewidth=2)

    axes[idx].set_title(f"Modelo N-HiTS vs Realidad - Serie: {serie}", fontweight='bold')
    axes[idx].set_ylabel("Ventas")
    axes[idx].set_ylim(bottom=0)
    axes[idx].legend(loc='upper left')

axes[-1].set_xlabel("Fecha (Semanas)", fontweight='bold')
plt.suptitle("Comparativa Visual: Dato Real vs N-HiTS (Evolución de FFNN)", fontsize=16, y=0.92)
plt.show()

# TABLA RESUMEN FINAL: COMPARATIVA DE TODOS LOS MODELOS VS sNAIVE

import pandas as pd
import numpy as np
from IPython.display import display

#  Calcular el MAE y RMSE del sNaive
errores_snaive = test_real.astype(float) - predicciones_snaive_test.astype(float)
mae_base = errores_snaive.abs().mean().mean()
rmse_base = ((errores_snaive ** 2).mean() ** 0.5).mean()

#  Metemos todas las predicciones de Deep Learning en un diccionario.
predicciones_dl = {
    'FFNN clásica (MLP)': predicciones_ffnn_nf,
    'LSTM (con Memoria Anual)': predicciones_lstm_nf,
    'N-HiTS (Jerárquico)': predicciones_nhits_nf,
}

resultados = []
resultados.append({
    'Modelo': 'Baseline (sNaive)',
    'MAE Medio': round(mae_base, 4),
    'RMSE Medio': round(rmse_base, 4),
    '% Mejora MAE': "0.00 %",
    '% Mejora RMSE': "0.00 %"
})

# Ahora para las arquitecturas neuronales
for nombre, preds in predicciones_dl.items():

    errores_dl = test_real.astype(float) - preds.astype(float)
    mae_dl = errores_dl.abs().mean().mean()
    rmse_dl = ((errores_dl ** 2).mean() ** 0.5).mean()

    # (Error Antiguo - Error Nuevo) / Error Antiguo * 100
    mejora_mae = ((mae_base - mae_dl) / mae_base) * 100
    mejora_rmse = ((rmse_base - rmse_dl) / rmse_base) * 100

    texto_mejora_mae = f"+{mejora_mae:.2f} %" if mejora_mae > 0 else f"{mejora_mae:.2f} %"
    texto_mejora_rmse = f"+{mejora_rmse:.2f} %" if mejora_rmse > 0 else f"{mejora_rmse:.2f} %"

    resultados.append({
        'Modelo': nombre,
        'MAE Medio': round(mae_dl, 4),
        'RMSE Medio': round(rmse_dl, 4),
        '% Mejora MAE': texto_mejora_mae,
        '% Mejora RMSE': texto_mejora_rmse
    })

df_resultados = pd.DataFrame(resultados)
df_resultados = df_resultados.sort_values(by='MAE Medio', ascending=True).reset_index(drop=True)

print(" RANKING FINAL DE MODELOS FRENTE A SEASONAL NAIVE (sNAIVE) ")
display(df_resultados)

!pip install hierarchicalforecast

# CREACIÓN DE LA JERARQUÍA (AGREGACIÓN POR PRODUCTO)

import pandas as pd
from hierarchicalforecast.utils import aggregate

df_hier = df_train_long.copy()

df_hier[['Store', 'Product']] = df_hier['unique_id'].str.split('_', expand=True)

df_hier = df_hier.drop(columns=['unique_id'])

hierarchy_levels = [
    ['Product'],
    ['Product', 'Store']
]

Y_df, S_df, tags = aggregate(df=df_hier, spec=hierarchy_levels)

Y_df['ds'] = pd.to_datetime(Y_df['ds'])

print(f"Total de series: {len(Y_df['unique_id'].unique())}")
print("Niveles creados:", list(tags.keys()))

print("\nMatriz S (Estructura de sumas):")
display(S_df.head())

# ENTRENAMIENTO DE MODELO BASE Y RECONCILIACIÓN JERÁRQUICA - NHITS

import pandas as pd
from neuralforecast import NeuralForecast
from neuralforecast.models import NHITS
from hierarchicalforecast.core import HierarchicalReconciliation
from hierarchicalforecast.methods import BottomUp, MinTrace

modelo_base = NHITS(h=1, input_size=15, max_steps=500, scaler_type='robust', random_seed=42)

nf_hier = NeuralForecast(models=[modelo_base], freq='W-MON')
nf_hier.fit(df=Y_df)

Y_hat_df = nf_hier.predict().reset_index()

reconciliadores = [
    BottomUp(),
    MinTrace(method='ols')
]

hrec = HierarchicalReconciliation(reconcilers=reconciliadores)

Y_rec_df = hrec.reconcile(Y_hat_df=Y_hat_df, S_df=S_df, tags=tags)

display(Y_rec_df.head(10))

# PREDICCIÓN WALK-FORWARD JERÁRQUICA (SOLO MINT) Y MÉTRICAS FINALES
import numpy as np
import pandas as pd
from hierarchicalforecast.utils import aggregate

columnas_oficiales = test_real_nf.columns.tolist()
preds_mint_hier = pd.DataFrame(index=test_real_nf.index, columns=columnas_oficiales, dtype=float)

ventana_df = df_hier.copy()

for i, fecha in enumerate(test_real_nf.index):
    # Agregar el historial hasta esta semana
    Y_df_step, S_step, tags_step = aggregate(df=ventana_df, spec=hierarchy_levels)
    Y_df_step['ds'] = pd.to_datetime(Y_df_step['ds'])

    # Predecir 1 paso hacia el futuro
    Y_hat_step = nf_hier.predict(df=Y_df_step).reset_index()

    # Reconciliación matemática
    Y_rec_step = hrec.reconcile(Y_hat_df=Y_hat_step, S_df=S_step, tags=tags_step)

    # Aislar solo las predicciones de nuestro nivel inferior (las tiendas)
    nivel_inferior_ids = tags_step['Product/Store']
    Y_inf = Y_rec_step[Y_rec_step['unique_id'].isin(nivel_inferior_ids)].copy()

    # Reconstruir el ID original para comparar con test_real_nf
    Y_inf['original_id'] = Y_inf['unique_id'].apply(lambda x: x.split('/')[1] + '_' + x.split('/')[0])

    # Guardar la predicción reconciliada
    mint_wide = Y_inf.pivot(index='ds', columns='original_id', values='NHITS/MinTrace_method-ols').iloc[0]
    preds_mint_hier.iloc[i, :] = np.maximum(mint_wide[columnas_oficiales].values, 0.0)

    # Actualizar el historial con el dato real de esta iteración
    fila_real = test_real_nf.iloc[[i]].copy()
    fila_real.index.name = 'ds'
    fila_real_long = fila_real.reset_index().melt(id_vars='ds', var_name='unique_id', value_name='y')
    fila_real_long['ds'] = pd.to_datetime(fila_real_long['ds'])

    # Se rompe el ID del dato real para que coincida con el formato de la jerarquía
    fila_real_long[['Store', 'Product']] = fila_real_long['unique_id'].str.split('_', expand=True)
    fila_real_long = fila_real_long.drop(columns=['unique_id'])

    ventana_df = pd.concat([ventana_df, fila_real_long], ignore_index=True)

    print(f" Semana {i+1}/8 completada: {fecha.date()}", end='\r')


# Error N-HiTS Reconciliado con MinT
err_mint = test_real_nf - preds_mint_hier
mae_mint = err_mint.abs().mean().mean()
rmse_mint = ((err_mint**2).mean()**0.5).mean()

print(f" N-HiTS Jerárquico (MinT): MAE = {mae_mint:.4f} | RMSE = {rmse_mint:.4f}")

# ENTRENAMIENTO DEL MODELO MLP SOBRE LA JERARQUÍA COMPLETA

import pandas as pd
from neuralforecast import NeuralForecast
from neuralforecast.models import MLP
from neuralforecast.losses.pytorch import DistributionLoss

modelo_ffnn_hier = MLP(
    h=1,
    input_size=15,
    loss=DistributionLoss(distribution='Poisson'),
    max_steps=500,
    scaler_type='robust',
    learning_rate=1e-3,
    random_seed=42
)

nf_hier_mlp = NeuralForecast(models=[modelo_ffnn_hier], freq='W-MON')
nf_hier_mlp.fit(df=Y_df)

# VERIFICACIÓN DE RECONCILIACIÓN (MINT)
from hierarchicalforecast.core import HierarchicalReconciliation
from hierarchicalforecast.methods import BottomUp, MinTrace

# Predicción base
Y_hat_mlp = nf_hier_mlp.predict().reset_index()

# Definimos reconciliadores
reconcilers = [
    BottomUp(),
    MinTrace(method='ols')
]

hrec = HierarchicalReconciliation(reconcilers=reconcilers)

# Reconciliamos
Y_rec_mlp = hrec.reconcile(Y_hat_df=Y_hat_mlp, S_df=S_df, tags=tags)

print(" Columnas generadas:")
print(Y_rec_mlp.columns.tolist())
display(Y_rec_mlp.head(3))

# PREDICCIÓN WALK-FORWARD JERÁRQUICA (FFNN + MinT)
import numpy as np
from hierarchicalforecast.utils import aggregate


columnas_oficiales = test_real_nf.columns.tolist()
preds_mint_ffnn = pd.DataFrame(index=test_real_nf.index, columns=columnas_oficiales, dtype=float)

ventana_df = df_hier.copy()

for i, fecha in enumerate(test_real_nf.index):

    Y_df_step, S_step, tags_step = aggregate(df=ventana_df, spec=hierarchy_levels)
    Y_df_step['ds'] = pd.to_datetime(Y_df_step['ds'])

    # Predicción con el modelo ya entrenado
    Y_hat_step = nf_hier_mlp.predict(df=Y_df_step).reset_index()

    # Reconciliación MinT
    Y_rec_step = hrec.reconcile(Y_hat_df=Y_hat_step, S_df=S_step, tags=tags_step)

    # Filtrar solo el nivel inferior (Producto/Store)
    nivel_tienda_ids = tags_step['Product/Store']
    Y_inf = Y_rec_step[Y_rec_step['unique_id'].isin(nivel_tienda_ids)].copy()

    # Reconstrucción del ID original ('Tienda_Producto')
    Y_inf['original_id'] = Y_inf['unique_id'].apply(lambda x: x.split('/')[1] + '_' + x.split('/')[0])

    # Guardar el valor reconciliado
    col_name = 'MLP/MinTrace_method-ols'
    mint_wide = Y_inf.pivot(index='ds', columns='original_id', values=col_name).iloc[0]
    preds_mint_ffnn.iloc[i, :] = np.maximum(mint_wide[columnas_oficiales].values, 0.0)

    # Actualizar ventana con el dato real para la siguiente semana
    fila_real = test_real_nf.iloc[[i]].copy()
    fila_real.index.name = 'ds'
    fila_real_long = fila_real.reset_index().melt(id_vars='ds', var_name='unique_id', value_name='y')
    fila_real_long['ds'] = pd.to_datetime(fila_real_long['ds'])
    fila_real_long[['Store', 'Product']] = fila_real_long['unique_id'].str.split('_', expand=True)
    fila_real_long = fila_real_long.drop(columns=['unique_id'])

    ventana_df = pd.concat([ventana_df, fila_real_long], ignore_index=True)

    print(f"  Semana {i+1}/8 completada: {fecha.date()}", end='\r')

err_ffnn = test_real_nf - preds_mint_ffnn
mae_ffnn = err_ffnn.abs().mean().mean()
rmse_ffnn = ((err_ffnn**2).mean()**0.5).mean()

print(f" RESULTADO FFNN JERÁRQUICO (MinT)")
print(f"MAE:  {mae_ffnn:.4f}")
print(f"RMSE: {rmse_ffnn:.4f}")

# ENTRENAMIENTO DEL MODELO LSTM SOBRE LA JERARQUÍA COMPLETA
import pandas as pd
from neuralforecast import NeuralForecast
from neuralforecast.models import LSTM
from neuralforecast.losses.pytorch import DistributionLoss

# Configuracion LSTM
modelo_lstm_hier = LSTM(
    h=1,
    input_size=15,
    encoder_hidden_size=64,
    loss=DistributionLoss(distribution='NegativeBinomial'),
    max_steps=1000,
    scaler_type='robust',
    learning_rate=1e-3,
    random_seed=42
)

# Entrenamos sobre el dataset agregado Y_df
nf_hier_lstm = NeuralForecast(models=[modelo_lstm_hier], freq='W-MON')
nf_hier_lstm.fit(df=Y_df)

# VERIFICACIÓN DE RECONCILIACIÓN LSTM (MINT)
from hierarchicalforecast.core import HierarchicalReconciliation
from hierarchicalforecast.methods import BottomUp, MinTrace

Y_hat_lstm = nf_hier_lstm.predict().reset_index()

hrec_lstm = HierarchicalReconciliation(reconcilers=[BottomUp(), MinTrace(method='ols')])
Y_rec_lstm = hrec_lstm.reconcile(Y_hat_df=Y_hat_lstm, S_df=S_df, tags=tags)

print("Columnas generadas:")
print(Y_rec_lstm.columns.tolist())

# PREDICCIÓN WALK-FORWARD JERÁRQUICA (LSTM + MinT)
import numpy as np
from hierarchicalforecast.utils import aggregate

columnas_oficiales = test_real_nf.columns.tolist()
preds_mint_lstm = pd.DataFrame(index=test_real_nf.index, columns=columnas_oficiales, dtype=float)

ventana_df = df_hier.copy()

for i, fecha in enumerate(test_real_nf.index):

    Y_df_step, S_step, tags_step = aggregate(df=ventana_df, spec=hierarchy_levels)
    Y_df_step['ds'] = pd.to_datetime(Y_df_step['ds'])

    # Predicción LSTM
    Y_hat_step = nf_hier_lstm.predict(df=Y_df_step).reset_index()

    # Reconciliación
    Y_rec_step = hrec_lstm.reconcile(Y_hat_df=Y_hat_step, S_df=S_step, tags=tags_step)

    # Filtrar nivel tienda
    nivel_tienda_ids = tags_step['Product/Store']
    Y_inf = Y_rec_step[Y_rec_step['unique_id'].isin(nivel_tienda_ids)].copy()

    # Reconstrucción de ID
    Y_inf['original_id'] = Y_inf['unique_id'].apply(lambda x: x.split('/')[1] + '_' + x.split('/')[0])

    # Extraer columna MinT
    col_name = 'LSTM/MinTrace_method-ols'
    mint_wide = Y_inf.pivot(index='ds', columns='original_id', values=col_name).iloc[0]
    preds_mint_lstm.iloc[i, :] = np.maximum(mint_wide[columnas_oficiales].values, 0.0)

    fila_real = test_real_nf.iloc[[i]].copy()
    fila_real.index.name = 'ds'
    fila_real_long = fila_real.reset_index().melt(id_vars='ds', var_name='unique_id', value_name='y')
    fila_real_long['ds'] = pd.to_datetime(fila_real_long['ds'])
    fila_real_long[['Store', 'Product']] = fila_real_long['unique_id'].str.split('_', expand=True)
    fila_real_long = fila_real_long.drop(columns=['unique_id'])

    ventana_df = pd.concat([ventana_df, fila_real_long], ignore_index=True)

    print(f"  Semana {i+1}/8 completada: {fecha.date()}", end='\r')

err_lstm = test_real_nf - preds_mint_lstm
mae_lstm = err_lstm.abs().mean().mean()
rmse_lstm = ((err_lstm**2).mean()**0.5).mean()


print(f" RESULTADO LSTM JERÁRQUICO (MinT)")
print(f"MAE:  {mae_lstm:.4f}")
print(f"RMSE: {rmse_lstm:.4f}")

# COMPARATIVA DE MAE Y RMSE DE LOS OCHO MODELOS
import matplotlib.pyplot as plt
import numpy as np

modelos = ['N-HiTS\nJerárquico', 'LSTM\nLocal', 'FFNN\nJerárquico', 'FFNN\nLocal',
           'Holt-Winters', 'N-HiTS\nLocal', 'LSTM\nJerárquico', 'sNaive']
mae  = [1.6580, 1.7168, 1.7259, 1.7374, 1.7733, 1.7933, 1.8587, 2.3184]
rmse = [2.0881, 2.0883, 2.0958, 2.1070, 2.2179, 2.1718, 2.1987, 2.9809]

x = np.arange(len(modelos))
ancho = 0.38

fig, ax = plt.subplots(figsize=(14, 6))
barras_mae  = ax.bar(x - ancho/2, mae,  ancho, label='MAE',  color='#1f77b4')
barras_rmse = ax.bar(x + ancho/2, rmse, ancho, label='RMSE', color='#d62728')

ax.axhline(y=2.3184, color='#1f77b4', linestyle=':', alpha=0.5, linewidth=1)
ax.axhline(y=2.9809, color='#d62728', linestyle=':', alpha=0.5, linewidth=1)

for barras in [barras_mae, barras_rmse]:
    for b in barras:
        altura = b.get_height()
        ax.annotate(f'{altura:.3f}', xy=(b.get_x() + b.get_width()/2, altura),
                    xytext=(0, 4), textcoords="offset points",
                    ha='center', va='bottom', fontsize=16, fontweight='bold')

ax.set_ylabel('Error (unidades vendidas)', fontweight='bold')
ax.set_title('Comparativa de MAE y RMSE de los ocho modelos', fontsize=14, fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(modelos, fontsize=15)
ax.legend(loc='upper left', fontsize=11)
ax.set_ylim(0, 3.4)
ax.grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.show()

# BOX PLOT: DISTRIBUCIÓN DEL MAE POR SERIE PARA LOS OCHO MODELOS
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# Recalculamos el MAE por serie de cada modelo (uno por cada una de las 599 series)

maes_por_serie = {
    'sNaive':            (test_real_nf - predicciones_snaive_test).abs().mean(),
    'Holt-Winters':      (test_real_nf - predicciones_hw_test).abs().mean(),
    'FFNN\nLocal':       (test_real_nf - predicciones_ffnn_nf).abs().mean(),
    'LSTM\nLocal':       (test_real_nf - predicciones_lstm_nf).abs().mean(),
    'N-HiTS\nLocal':     (test_real_nf - predicciones_nhits_nf).abs().mean(),
    'FFNN\nJerárq.':     (test_real_nf - preds_mint_ffnn).abs().mean(),
    'LSTM\nJerárq.':     (test_real_nf - preds_mint_lstm).abs().mean(),
    'N-HiTS\nJerárq.':   (test_real_nf - preds_mint_hier).abs().mean(),
}

# Ordenamos de menor a mayor MAE medio (mismo orden que el ranking)
orden = sorted(maes_por_serie.keys(), key=lambda k: maes_por_serie[k].mean())
datos = [maes_por_serie[k].values for k in orden]

fig, ax = plt.subplots(figsize=(14, 7))

bp = ax.boxplot(datos, labels=orden, patch_artist=True,
                showfliers=True,          # mostrar outliers
                showmeans=True,           # mostrar la media (además de la mediana)
                meanprops={'marker':'D', 'markerfacecolor':'white',
                           'markeredgecolor':'black', 'markersize':6},
                medianprops={'color':'black', 'linewidth':1.5},
                flierprops={'marker':'o', 'markersize':3, 'alpha':0.3})

colores = plt.cm.viridis(np.linspace(0.15, 0.85, len(orden)))
for parche, color in zip(bp['boxes'], colores):
    parche.set_facecolor(color)
    parche.set_alpha(0.7)

ax.set_ylabel('MAE por serie', fontweight='bold', fontsize=12)
ax.set_title('Distribución del MAE por serie en los ocho modelos',
             fontsize=14, fontweight='bold')
ax.grid(axis='y', alpha=0.3)
ax.set_ylim(0, 5)

ax.legend([bp['means'][0]], ['Media'], loc='upper right', fontsize=10)
plt.tight_layout()
plt.show()

# COMPARACIÓN VISUAL: N-HiTS LOCAL vs N-HiTS JERÁRQUICO (MinT)
import matplotlib.pyplot as plt
import numpy as np

np.random.seed(2024)
series_vis = np.random.choice(columnas_oficiales, 4, replace=False)

fig, axes = plt.subplots(nrows=4, ncols=1, figsize=(14, 16), sharex=True)
fig.subplots_adjust(hspace=0.4)

for idx, serie in enumerate(series_vis):
    contexto = historico[serie].iloc[-20:].astype(float)

    # Histórico reciente
    axes[idx].plot(contexto.index, contexto,
                   label='Histórico Reciente', color='#555555', marker='o', markersize=4)
    # Dato real del test
    axes[idx].plot(test_real_nf.index, test_real_nf[serie],
                   label='Test (Dato Real)', color='#2ca02c', marker='o', linewidth=2.5)
    # N-HiTS local
    axes[idx].plot(predicciones_nhits_nf.index, predicciones_nhits_nf[serie],
                   label='N-HiTS Local', color='#1f77b4', linestyle='--', marker='s', linewidth=2)
    # N-HiTS jerárquico (reconciliado con MinT)
    axes[idx].plot(preds_mint_hier.index, preds_mint_hier[serie],
                   label='N-HiTS Jerárquico (MinT)', color='#d62728', linestyle='--', marker='x', linewidth=2)

    axes[idx].set_title(f"N-HiTS: Local vs Jerárquico - Serie: {serie}", fontweight='bold')
    axes[idx].set_ylabel("Ventas")
    axes[idx].set_ylim(bottom=0)
    axes[idx].legend(loc='upper left')

axes[-1].set_xlabel("Fecha (Semanas)", fontweight='bold')
plt.suptitle("Comparativa Visual: N-HiTS Local vs N-HiTS Jerárquico (MinT)", fontsize=16, y=0.92)
plt.show()

# COMPARACIÓN VISUAL: LSTM LOCAL vs LSTM JERÁRQUICO (MinT)
import matplotlib.pyplot as plt
import numpy as np

np.random.seed(2024)
series_vis = np.random.choice(columnas_oficiales, 4, replace=False)

fig, axes = plt.subplots(nrows=4, ncols=1, figsize=(14, 16), sharex=True)
fig.subplots_adjust(hspace=0.4)

for idx, serie in enumerate(series_vis):
    contexto = historico[serie].iloc[-20:].astype(float)

    # Histórico reciente
    axes[idx].plot(contexto.index, contexto,
                   label='Histórico Reciente', color='#555555', marker='o', markersize=4)
    # Dato real del test
    axes[idx].plot(test_real_nf.index, test_real_nf[serie],
                   label='Test (Dato Real)', color='#2ca02c', marker='o', linewidth=2.5)
    # LSTM local
    axes[idx].plot(predicciones_lstm_nf.index, predicciones_lstm_nf[serie],
                   label='LSTM Local', color='#1f77b4', linestyle='--', marker='s', linewidth=2)
    # LSTM jerárquico (reconciliado con MinT)
    axes[idx].plot(preds_mint_lstm.index, preds_mint_lstm[serie],
                   label='LSTM Jerárquico (MinT)', color='#d62728', linestyle='--', marker='x', linewidth=2)

    axes[idx].set_title(f"LSTM: Local vs Jerárquico - Serie: {serie}", fontweight='bold')
    axes[idx].set_ylabel("Ventas")
    axes[idx].set_ylim(bottom=0)
    axes[idx].legend(loc='upper left')

axes[-1].set_xlabel("Fecha (Semanas)", fontweight='bold')
plt.suptitle("Comparativa Visual: LSTM Local vs LSTM Jerárquico (MinT)", fontsize=16, y=0.92)
plt.show()

# SIMULACIÓN DE IMPACTO EMPRESARIAL (CAMPEONATO FINAL)

import numpy as np
import pandas as pd

# Función de cálculo de penalizaciones
def calcular_costes_inventario(df_real, df_pred, h, p):
    # Sobrante
    sobrante = np.maximum(0, df_pred - df_real)
    # Rotura
    rotura = np.maximum(0, df_real - df_pred)

    # Pesos de penalización 'h' y 'p'
    coste_holding = (sobrante * h).sum().sum()
    coste_shortage = (rotura * p).sum().sum()

    return coste_holding + coste_shortage

modelos_a_evaluar = {
    # Baselines
    "SNaive (Baseline)": predicciones_snaive_test,
    "Holt-Winters (Baseline)": predicciones_hw_test,

    # Deep Learning local
    "FFNN (Local)": predicciones_ffnn_nf,
    "LSTM (Local)": predicciones_lstm_nf,
    "N-HiTS (Local)": predicciones_nhits_nf,

    # Deep Learning jerárquico
    "FFNN (Jerárquico)": preds_mint_ffnn,
    "LSTM (Jerárquico)": preds_mint_lstm,
    "N-HiTS (Jerárquico)": preds_mint_hier
}

# Escenarios de negocio
escenarios = {
    "Escenario 1: Equilibrado (h=1, p=1)": {"h": 1, "p": 1},
    "Escenario 2: Servicio Crítico (h=1, p=5)": {"h": 1, "p": 5},
    "Escenario 3: Almacén Caro (h=5, p=1)": {"h": 5, "p": 1}
}

# Resultados
resultados_costes = pd.DataFrame(index=modelos_a_evaluar.keys(), columns=escenarios.keys())

for nombre_escenario, parametros in escenarios.items():
    h = parametros['h']
    p = parametros['p']

    for nombre_modelo, predicciones in modelos_a_evaluar.items():
        coste = calcular_costes_inventario(test_real_nf, predicciones, h, p)
        resultados_costes.loc[nombre_modelo, nombre_escenario] = coste

tabla_bonita = resultados_costes.astype(float).style \
    .format("{:,.2f}") \
    .highlight_min(axis=0, color='lightgreen') \
    .set_caption("Coste Total de Inventario (Unidades de Penalización)") \
    .set_properties(**{'text-align': 'center', 'border': '1px solid black'}) \
    .set_table_styles([

        {'selector': 'thead th',
         'props': [('text-align', 'center'), ('font-weight', 'bold'),
                   ('background-color', '#4c72b0'), ('color', 'white'),
                   ('border', '1px solid black')]},

        {'selector': 'tbody th',
         'props': [('text-align', 'left'), ('font-weight', 'bold'),
                   ('background-color', '#dce6f1'), ('color', 'black'),
                   ('border', '1px solid black')]},

        {'selector': 'caption',
         'props': [('font-size', '16px'), ('font-weight', 'bold'),
                   ('margin-bottom', '10px'), ('color', 'black')]}
    ])

display(tabla_bonita)

# COSTE TOTAL DE INVENTARIO POR MODELO Y ESCENARIO
import matplotlib.pyplot as plt
import numpy as np

modelos = ['sNaive', 'Holt-Winters', 'FFNN\nLocal', 'LSTM\nLocal', 'N-HiTS\nLocal',
           'FFNN\nJerárq.', 'LSTM\nJerárq.', 'N-HiTS\nJerárq.']

equilibrado = [11110.00, 8497.88, 8325.83, 8226.78, 8593.31, 8270.69, 8907.06, 7945.06]
servicio    = [28706.00, 23334.68, 23611.11, 24449.74, 23733.60, 23227.74, 22883.66, 25928.44]
almacen     = [37954.00, 27652.63, 26343.88, 24910.93, 27826.25, 26396.43, 30558.70, 21741.89]

x = np.arange(len(modelos))
ancho = 0.27

fig, ax = plt.subplots(figsize=(15, 6))
ax.bar(x - ancho, equilibrado, ancho, label='Equilibrado (h=1, p=1)', color='#4c72b0')
ax.bar(x,         servicio,    ancho, label='Servicio crítico (h=1, p=5)', color='#dd8452')
ax.bar(x + ancho, almacen,     ancho, label='Almacén caro (h=5, p=1)', color='#55a868')

ax.set_ylabel('Coste total (unidades de penalización)', fontweight='bold')
ax.set_title('Coste total de inventario por modelo y escenario', fontsize=13, fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(modelos, fontsize=14)
ax.legend(loc='upper right')
ax.grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.show()